name: Deploy
on: 
  workflow_call:
    inputs:
      account_id:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  deploy:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: node environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: install
        run: npm ci
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::447002520154:role/github-deploy-role-cicd
          aws-region: eu-west-1
      - name: start deployment
        uses: bobheadxi/deployments@v1.2.0
        id: deployment
        with:
          step: start
          env: release
      - name: ${{ inputs.environment }} deploy
        env:
          ACCOUNT_ID: ${{ inputs.account_id }}
          ACCOUNT_NAME: ${{ inputs.environment }}
        run: npm run deploy
      - name: update deployment status
        uses: bobheadxi/deployments@v1.2.0
        with:
          step: finish
          status: ${{ job.status }}
          env: cici.${{ inputs.environment }}.awscommunitybuilders.org
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
