name: Deploy

on:
  push:
    branches: [main]

jobs:
  test:
    name: test
    uses: aws-community-projects/cicd/.github/workflows/test.yml@main
  deploy-sandbox:
    needs: test
    name: deploy to sandbox
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: node environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::447002520154:role/github-oidc-stack-DeployRole885297C3-1VVRDT551FCCC
          aws-region: eu-west-1
      - name: cdk deploy
        run: |
          npm ci && npm run deploy
