name: Deploy

on:
  push:
    branches: [main]

jobs:
  test:
    name: test
    uses: aws-community-projects/cicd/.github/workflows/test.yml@main
  deploy-sandbox:
    name: deploy to sandbox
    needs: test
    uses: aws-community-projects/cicd/.github/workflows/deploy.yml@main
    with:
      account_id: '799776970420'
      environment: sandbox
  deploy-test:
    name: deploy to test
    needs: deploy-sandbox
    uses: aws-community-projects/cicd/.github/workflows/deploy.yml@main
    with:
      account_id: '012208286009'
      environment: test
  deploy-production:
    name: deploy to production
    needs: deploy-test
    uses: aws-community-projects/cicd/.github/workflows/deploy.yml@main
    with:
      account_id: '865725118528'
      environment: production
