name: Deploy

on:
  push:
    branches: [main]

jobs:
  test:
    name: test
    uses: aws-community-projects/cicd/.github/workflows/test.yml
  deploy-sandbox:
    name: deploy to sandbox
    needs: test
    environment: sandbox
    runs-on: ubuntu-latest
    steps:
      - uses: aws-community-projects/cicd/.github/workflows/deploy.yml
        with:
          account-id: '799776970420'
          environment: sandbox
  deploy-test:
    name: deploy to test
    needs: deploy-sandbox
    environment: test
    runs-on: ubuntu-latest
    steps:
      - uses: aws-community-projects/cicd/.github/workflows/deploy.yml
        with:
          account-id: '012208286009'
          environment: test
  deploy-production:
    name: deploy to production
    needs: deploy-sandbox
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: aws-community-projects/cicd/.github/workflows/deploy.yml
        with:
          account-id: '865725118528'
          environment: production
